version: "3"

services:
  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - "./frontend:/projects/frontend"
    tty: true
    entrypoint:
      - sh
    command:
      - -c
      - |
        npm install
        ng serve --host 0.0.0.0 --disable-host-check --hmr --proxy-config proxy.conf.json
